CREATE TABLE [dbo].[Users]
(
	[UserId] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserName] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(150) NOT NULL,
	[Password] VARCHAR(70) NOT NULL,
	[CellPhone] VARCHAR(50) NOT NULL,
	[LastUpdated] DATETIME NOT NULL DEFAULT GETDATE(),
	[Available] BIT NOT NULL DEFAULT '1'
)