//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForgot.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryPhones
    {
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string Code { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool Available { get; set; }
    }
}
